### ISSUE TITLE
Auto generate blueprint images

### ISSUE THREAD

**Issue by combe15** [combe15/factorio-whiteboard#55]
Need to find or make a way to auto-generate images for every blueprint in the static website.

**Comment by chi-feng** [comment]
This is the repository for the code behind the Blueprint Bot (discord, reddit, web API)
https://github.com/demodude4u/Factorio-FBSR
This requires a dependency https://github.com/demodude4u/Java-Factorio-Data-Wrapper

If someone can write out the installation and operating instructions for running the web API https://github.com/demodude4u/Factorio-FBSR/blob/master/FactorioBlueprintStringRenderer/src/com/demod/fbsr/app/WebAPIService.java

I can turn it into a Docker image and run it as a service behind a caching layer (so repeat blueprint requests get served from cache). 

I just don't know enough about building java projects from the command-line to run the code.

**Comment by chi-feng** [comment]
I will try to self-host the FBSR and update the gen_indexes.py script to fetch BP images. https://gitlab.com/jeff-s/fbsr

**Comment by chi-feng** [comment]
This issue is closed by https://github.com/combe15/factorio-whiteboard/pull/69
